/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.Aluno;
import classes.Professor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Alisson Jaques
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * @return the listAlunos
     */
    public List<Aluno> getListAlunos() {
        return listAlunos;
    }

    /**
     * @param listAlunos the listAlunos to set
     */
    public void setListAlunos(List<Aluno> listAlunos) {
        this.listAlunos = listAlunos;
    }

    /**
     * @return the listProfessores
     */
    public List<Professor> getListProfessores() {
        return listProfessores;
    }

    /**
     * @param listProfessores the listProfessores to set
     */
    public void setListProfessores(List<Professor> listProfessores) {
        this.listProfessores = listProfessores;
    }
    
    private List<Aluno> listAlunos;
    private List<Professor> listProfessores;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        listAlunos = new ArrayList<>();
        listProfessores = new ArrayList<>();
    }
    
    /**
     * @return the mCadastro
     */
    public javax.swing.JMenu getmCadastro() {
        return mCadastro;
    }

    /**
     * @param mCadastro the mCadastro to set
     */
    public void setmCadastro(javax.swing.JMenu mCadastro) {
        this.mCadastro = mCadastro;
    }

    /**
     * @return the mLogin
     */
    public javax.swing.JMenu getmLogin() {
        return mLogin;
    }

    /**
     * @param mLogin the mLogin to set
     */
    public void setmLogin(javax.swing.JMenu mLogin) {
        this.mLogin = mLogin;
    }

    /**
     * @return the mbCadastro
     */
    public javax.swing.JMenuBar getMbCadastro() {
        return mbCadastro;
    }

    /**
     * @param mbCadastro the mbCadastro to set
     */
    public void setMbCadastro(javax.swing.JMenuBar mbCadastro) {
        this.mbCadastro = mbCadastro;
    }

    /**
     * @return the miAlunos
     */
    public javax.swing.JMenuItem getMiAlunos() {
        return miAlunos;
    }

    /**
     * @param miAlunos the miAlunos to set
     */
    public void setMiAlunos(javax.swing.JMenuItem miAlunos) {
        this.miAlunos = miAlunos;
    }

    /**
     * @return the miLogin
     */
    public javax.swing.JMenuItem getMiLogin() {
        return miLogin;
    }

    /**
     * @param miLogin the miLogin to set
     */
    public void setMiLogin(javax.swing.JMenuItem miLogin) {
        this.miLogin = miLogin;
    }

    /**
     * @return the miProfessores
     */
    public javax.swing.JMenuItem getMiProfessores() {
        return miProfessores;
    }

    /**
     * @param miProfessores the miProfessores to set
     */
    public void setMiProfessores(javax.swing.JMenuItem miProfessores) {
        this.miProfessores = miProfessores;
    }

    /**
     * @return the miSair
     */
    public javax.swing.JMenuItem getMiSair() {
        return miSair;
    }

    /**
     * @param miSair the miSair to set
     */
    public void setMiSair(javax.swing.JMenuItem miSair) {
        this.miSair = miSair;
    }

    /**
     * @return the pPrincipal
     */
    public javax.swing.JPanel getpPrincipal() {
        return pPrincipal;
    }

    /**
     * @param pPrincipal the pPrincipal to set
     */
    public void setpPrincipal(javax.swing.JPanel pPrincipal) {
        this.pPrincipal = pPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPrincipal = new javax.swing.JPanel();
        mbCadastro = new javax.swing.JMenuBar();
        mLogin = new javax.swing.JMenu();
        miLogin = new javax.swing.JMenuItem();
        miSair = new javax.swing.JMenuItem();
        mCadastro = new javax.swing.JMenu();
        miAlunos = new javax.swing.JMenuItem();
        miProfessores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Cadastro Acadêmico");

        javax.swing.GroupLayout pPrincipalLayout = new javax.swing.GroupLayout(pPrincipal);
        pPrincipal.setLayout(pPrincipalLayout);
        pPrincipalLayout.setHorizontalGroup(
            pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );
        pPrincipalLayout.setVerticalGroup(
            pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        mLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        mLogin.setText("Login");

        miLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        miLogin.setText("Login");
        miLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLoginActionPerformed(evt);
            }
        });
        mLogin.add(miLogin);

        miSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        miSair.setText("Sair");
        miSair.setEnabled(false);
        miSair.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                miSairAncestorResized(evt);
            }
        });
        miSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSairActionPerformed(evt);
            }
        });
        mLogin.add(miSair);

        mbCadastro.add(mLogin);

        mCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group_add.png"))); // NOI18N
        mCadastro.setText("Cadastro");
        mCadastro.setEnabled(false);

        miAlunos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        miAlunos.setText("Alunos");
        miAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAlunosActionPerformed(evt);
            }
        });
        mCadastro.add(miAlunos);

        miProfessores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        miProfessores.setText("Professores");
        miProfessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProfessoresActionPerformed(evt);
            }
        });
        mCadastro.add(miProfessores);

        mbCadastro.add(mCadastro);

        setJMenuBar(mbCadastro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miProfessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProfessoresActionPerformed
        TelaCadastroProfessor tcp = new TelaCadastroProfessor(getListProfessores());
        tcp.setVisible(true);
    }//GEN-LAST:event_miProfessoresActionPerformed

    private void miAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAlunosActionPerformed
       TelaCadastroAluno1 tca = new TelaCadastroAluno1(getListAlunos());
       tca.setVisible(true);
    }//GEN-LAST:event_miAlunosActionPerformed

    private void miLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLoginActionPerformed
       TelaLogin tl = new TelaLogin(this,true);
       tl.setVisible(true);
    }//GEN-LAST:event_miLoginActionPerformed

    private void miSairAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_miSairAncestorResized
               // TODO add your handling code here:
    }//GEN-LAST:event_miSairAncestorResized

    private void miSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSairActionPerformed
        int op = JOptionPane.showConfirmDialog(this, "Deseja mesmo sair do sistema?", "Sair", JOptionPane.OK_CANCEL_OPTION);

        if (op == 0) {
            dispose();
        }
    }//GEN-LAST:event_miSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu mCadastro;
    private javax.swing.JMenu mLogin;
    private javax.swing.JMenuBar mbCadastro;
    private javax.swing.JMenuItem miAlunos;
    private javax.swing.JMenuItem miLogin;
    private javax.swing.JMenuItem miProfessores;
    private javax.swing.JMenuItem miSair;
    private javax.swing.JPanel pPrincipal;
    // End of variables declaration//GEN-END:variables
}
