/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.Aluno;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ericd
 */
public class TelaCadastroAluno1 extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroAluno
     */
    private List<Aluno> listAlunos;
    private boolean alterar;

    /**
     * @return the listAlunos
     */
    public List<Aluno> getListAlunos() {
        return listAlunos;
    }

    /**
     * @param listAlunos the listAlunos to set
     */
    public void setListAlunos(List<Aluno> listAlunos) {
        this.listAlunos = listAlunos;
    }

    public TelaCadastroAluno1(List<Aluno> listAlunos) {
        this.listAlunos = listAlunos;
        alterar = false;
        initComponents();
        preencherTabelaAluno();
    }
    
    private void preencherTabelaAluno(){
        
        if(!getListAlunos().isEmpty()){
            
            DefaultTableModel model = (DefaultTableModel) getTbAluno().getModel();
            
            for (Aluno aluno : getListAlunos()) {
                model.addRow(new Object[]{aluno.getCpf(), aluno.getNome(), aluno.getMatricula(), aluno.getCurso()});
            }
            
        }   
    }

    private void limparDados() {
        getCbDepartamento().setSelectedIndex(-1);
        getFtfCpf().setText("");
        getFtfDataNasc().setText("");
        getFtfMatricula().setText("");
        getRbMasc().setSelected(true);
        getTfEndereco().setText("");
        getTfNome().setText("");
        getBtnAlterar().setEnabled(false);
        getBtnExcluir().setEnabled(false);
        getFtfCpf().setEnabled(true);
        getTbAluno().setEnabled(true);
        getTbAluno().getSelectionModel().removeSelectionInterval(0, getTbAluno().getRowCount());
        alterar = false;
    }

    private void preencherDados(Aluno aluno) {

        getFtfCpf().setText(aluno.getCpf());

        DateFormat df = new SimpleDateFormat("dd/mm/yyyy");
        String DataNasc = df.format(aluno.getDataNasc());
        getFtfDataNasc().setText(DataNasc);

        getFtfMatricula().setText(aluno.getMatricula());

        if (aluno.getSexo() == 'M') {
            getRbMasc().setSelected(true);
        } else {
            getRbFem().setSelected(true);
        }

        getTfEndereco().setText(aluno.getEndereco());
        getTfNome().setText(aluno.getNome());

        int quantDep = getCbDepartamento().getItemCount();

        for (int i = 0; i < quantDep; i++) {
            String dep = getCbDepartamento().getItemAt(i);
            if (dep.equals(aluno.getDepartamento())) {
                getCbDepartamento().setSelectedIndex(i);
                break;
            }
        }

        int quantCurso = getCbCurso().getItemCount();

        for (int i = 0; i < quantCurso; i++) {
            String curso = getCbCurso().getItemAt(i);
            if (curso.equals(aluno.getCurso())) {
                getCbCurso().setSelectedIndex(i);
                break;
            }
        }

        getFtfCpf().setEnabled(false);
    }

    private boolean validarDados() {
        boolean valid = true;

        if (getCbDepartamento().getSelectedIndex() < 0) {
            valid = false;
        } else if (getCbCurso().getSelectedIndex() < 0) {
            valid = false;
        } else if (getFtfCpf().getText().isEmpty()) {
            valid = false;
        } else if (getFtfDataNasc().getText().isEmpty()) {
            valid = false;
        } else if (getFtfMatricula().getText().isEmpty()) {
            valid = false;
        } else if (getTfEndereco().getText().isEmpty()) {
            valid = false;
        } else if (getTfNome().getText().isEmpty()) {
            valid = false;
        }

        if (!valid) {
            JOptionPane.showMessageDialog(this, "Favor, preenger todos os campos do cadastro de alunos!", "Erro ao cadastrar aluno", JOptionPane.ERROR_MESSAGE);
        }

        return valid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        pInfBasicas = new javax.swing.JPanel();
        lNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lCpf = new javax.swing.JLabel();
        ftfCpf = new javax.swing.JFormattedTextField();
        lDataNasc = new javax.swing.JLabel();
        ftfDataNasc = new javax.swing.JFormattedTextField();
        lEndereco = new javax.swing.JLabel();
        tfEndereco = new javax.swing.JTextField();
        pSexo = new javax.swing.JPanel();
        rbMasc = new javax.swing.JRadioButton();
        rbFem = new javax.swing.JRadioButton();
        pInfAluno = new javax.swing.JPanel();
        lMatricula = new javax.swing.JLabel();
        ftfMatricula = new javax.swing.JFormattedTextField();
        lbDepartamento = new javax.swing.JLabel();
        cbDepartamento = new javax.swing.JComboBox<>();
        lCurso = new javax.swing.JLabel();
        cbCurso = new javax.swing.JComboBox<>();
        pBotoes = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pTabelaAluno = new javax.swing.JPanel();
        spTabelaAluno = new javax.swing.JScrollPane();
        tbAluno = new javax.swing.JTable();
        pBotoesTabela = new javax.swing.JPanel();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Alunos");
        setResizable(false);

        pInfBasicas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Informações Básicas ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        lNome.setText("Nome: ");

        lCpf.setText("CPF: ");

        try {
            ftfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lDataNasc.setText("Data de nascimento: ");

        ftfDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        lEndereco.setText("Endereço: ");

        pSexo.setBorder(javax.swing.BorderFactory.createTitledBorder(" Sexo "));

        bgSexo.add(rbMasc);
        rbMasc.setSelected(true);
        rbMasc.setText("Masculino");

        bgSexo.add(rbFem);
        rbFem.setText("Feminino");

        javax.swing.GroupLayout pSexoLayout = new javax.swing.GroupLayout(pSexo);
        pSexo.setLayout(pSexoLayout);
        pSexoLayout.setHorizontalGroup(
            pSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSexoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbMasc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbFem)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pSexoLayout.setVerticalGroup(
            pSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rbMasc)
                .addComponent(rbFem))
        );

        javax.swing.GroupLayout pInfBasicasLayout = new javax.swing.GroupLayout(pInfBasicas);
        pInfBasicas.setLayout(pInfBasicasLayout);
        pInfBasicasLayout.setHorizontalGroup(
            pInfBasicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInfBasicasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pInfBasicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pInfBasicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pInfBasicasLayout.createSequentialGroup()
                            .addComponent(lNome)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfNome))
                        .addGroup(pInfBasicasLayout.createSequentialGroup()
                            .addComponent(lCpf)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lDataNasc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ftfDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pInfBasicasLayout.createSequentialGroup()
                        .addComponent(lEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pInfBasicasLayout.setVerticalGroup(
            pInfBasicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInfBasicasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pInfBasicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pInfBasicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCpf)
                    .addComponent(lDataNasc)
                    .addComponent(ftfDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pInfBasicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        pInfAluno.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Informações Aluno ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        lMatricula.setText("Matricula: ");

        try {
            ftfMatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbDepartamento.setText("Departamento: ");

        cbDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ciências Sociais", "Cências Humanas", "Exatas", "Engenharias" }));
        cbDepartamento.setSelectedIndex(-1);
        cbDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDepartamentoActionPerformed(evt);
            }
        });

        lCurso.setText("Curso: ");

        cbCurso.setEnabled(false);

        javax.swing.GroupLayout pInfAlunoLayout = new javax.swing.GroupLayout(pInfAluno);
        pInfAluno.setLayout(pInfAlunoLayout);
        pInfAlunoLayout.setHorizontalGroup(
            pInfAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInfAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pInfAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pInfAlunoLayout.createSequentialGroup()
                        .addComponent(lMatricula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pInfAlunoLayout.createSequentialGroup()
                        .addComponent(lbDepartamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pInfAlunoLayout.createSequentialGroup()
                        .addComponent(lCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pInfAlunoLayout.setVerticalGroup(
            pInfAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInfAlunoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pInfAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMatricula)
                    .addComponent(ftfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pInfAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDepartamento)
                    .addComponent(cbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pInfAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lCurso)
                    .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnOk.setText("Confirmar");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pBotoesLayout = new javax.swing.GroupLayout(pBotoes);
        pBotoes.setLayout(pBotoesLayout);
        pBotoesLayout.setHorizontalGroup(
            pBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
        );
        pBotoesLayout.setVerticalGroup(
            pBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBotoesLayout.createSequentialGroup()
                .addGroup(pBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnOk))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        tbAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Nome", "Mátricula", "Curso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbAluno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbAlunoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tbAlunoFocusLost(evt);
            }
        });
        tbAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAlunoMouseClicked(evt);
            }
        });
        spTabelaAluno.setViewportView(tbAluno);
        if (tbAluno.getColumnModel().getColumnCount() > 0) {
            tbAluno.getColumnModel().getColumn(0).setPreferredWidth(80);
            tbAluno.getColumnModel().getColumn(1).setPreferredWidth(120);
            tbAluno.getColumnModel().getColumn(2).setPreferredWidth(70);
            tbAluno.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        javax.swing.GroupLayout pTabelaAlunoLayout = new javax.swing.GroupLayout(pTabelaAluno);
        pTabelaAluno.setLayout(pTabelaAlunoLayout);
        pTabelaAlunoLayout.setHorizontalGroup(
            pTabelaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTabelaAlunoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(spTabelaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pTabelaAlunoLayout.setVerticalGroup(
            pTabelaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spTabelaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_edit.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pBotoesTabelaLayout = new javax.swing.GroupLayout(pBotoesTabela);
        pBotoesTabela.setLayout(pBotoesTabelaLayout);
        pBotoesTabelaLayout.setHorizontalGroup(
            pBotoesTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBotoesTabelaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pBotoesTabelaLayout.setVerticalGroup(
            pBotoesTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBotoesTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pBotoesTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pTabelaAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pBotoesTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(pInfBasicas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pInfAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pBotoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pInfBasicas, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pInfAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pTabelaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pBotoesTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDepartamentoActionPerformed

        getCbCurso().setModel(new DefaultComboBoxModel<>());

        if (getCbDepartamento().getSelectedIndex() >= 0) {

            getCbCurso().setEnabled(true);

            switch (getCbDepartamento().getSelectedIndex()) {

                case 0:
                    getCbCurso().addItem("Psicologia");
                    getCbCurso().addItem("Filosofia");
                    getCbCurso().addItem("Ciências da Informação");
                    break;
                case 1:
                    getCbCurso().addItem("Medicina");
                    getCbCurso().addItem("Enfermagem");
                    getCbCurso().addItem("Odontologia");
                    getCbCurso().addItem("Nutrição");
                    getCbCurso().addItem("Biomedicina");
                    break;
                case 2:
                    getCbCurso().addItem("Matemática");
                    getCbCurso().addItem("Física");
                    getCbCurso().addItem("Estatística");
                    break;
                case 3:
                    getCbCurso().addItem("Engenharia Civil");
                    getCbCurso().addItem("Engenharia de Controle e Automação");
                    getCbCurso().addItem("Engenharia da Computação");
                    getCbCurso().addItem("Engenharia de Minas");
                    break;

            }

        } else {
            getCbCurso().setEnabled(false);
        }

    }//GEN-LAST:event_cbDepartamentoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        int op = JOptionPane.showConfirmDialog(this, "Deseja mesmo sair do cadastro de alunos?", "Confirmação", JOptionPane.YES_NO_OPTION);

        if (op == 0) {
            dispose();
        }

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed

        if (validarDados()) {
            Aluno aluno = new Aluno();
            aluno.setCpf(getFtfCpf().getText());

            int index = getListAlunos().indexOf(aluno);

            if (index > -1) {
                if (!alterar) {
                    JOptionPane.showMessageDialog(this, "Já existe um aluno com esse cpf!", "Erro ao cadastrar aluno", JOptionPane.ERROR_MESSAGE);
                    return;
                } else {
                    aluno = getListAlunos().get(index);
                }
            }
            
            aluno.setNome(getTfNome().getText());
            String dataNasc = getFtfDataNasc().getText();
            DateFormat df = new SimpleDateFormat("dd/mm/yyyy");

            try {
                aluno.setDataNasc(df.parse(dataNasc));
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Favor, inserir uma data de nascimento valida!", "Erro ao cadastrar aluno", JOptionPane.ERROR_MESSAGE);
                return;
            }

            aluno.setEndereco(getTfEndereco().getText());

            if (getRbMasc().isSelected()) {
                aluno.setSexo('M');
            } else {
                aluno.setSexo('F');
            }

            aluno.setMatricula(getFtfMatricula().getText());
            aluno.setDepartamento((String) getCbDepartamento().getSelectedItem());
            aluno.setCurso((String) getCbCurso().getSelectedItem());

            DefaultTableModel model = (DefaultTableModel) getTbAluno().getModel();

            String msg = "";
            
            if (!alterar) {
                msg = "Aluno cadastrado com sucesso!";
                getListAlunos().add(aluno);
                model.addRow(new Object[]{aluno.getCpf(), aluno.getNome(), aluno.getMatricula(), aluno.getCurso()});
            } else {
                msg = "Alteração cadastral de aluno realizada com sucesso!";
                model.setValueAt(aluno.getNome(), index, 1);
                model.setValueAt(aluno.getMatricula(), index, 2);
                model.setValueAt(aluno.getCurso(), index, 3);
            }

            JOptionPane.showMessageDialog(this, msg, "Confirmação de cadastro", JOptionPane.INFORMATION_MESSAGE);

            limparDados();

            System.out.println(getListAlunos());
        }

    }//GEN-LAST:event_btnOkActionPerformed

    private void tbAlunoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbAlunoFocusGained
        if (getTbAluno().getSelectedRow() > -1) {
            getBtnAlterar().setEnabled(true);
            getBtnExcluir().setEnabled(true);
        }
    }//GEN-LAST:event_tbAlunoFocusGained

    private void tbAlunoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbAlunoFocusLost
        if (getTbAluno().getSelectedRow() < 0) {
            getBtnExcluir().setEnabled(false);
            getBtnAlterar().setEnabled(false);
        }
    }//GEN-LAST:event_tbAlunoFocusLost

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int op = JOptionPane.showConfirmDialog(this, "Deseja mesmo excluir o usuário selecionado?", "Confirmação", JOptionPane.YES_NO_OPTION);

        if (op == 0) {
            excluirAluno();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        if(getTbAluno().getSelectedRow() > -1)
            alterarAluno();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void alterarAluno(){
        DefaultTableModel model = (DefaultTableModel) getTbAluno().getModel();
        String cpf = (String) model.getValueAt(getTbAluno().getSelectedRow(), 0);

        Aluno aluno = new Aluno();
        aluno.setCpf(cpf);
        int index = getListAlunos().indexOf(aluno);

        if (index > -1) {
            aluno = getListAlunos().get(index);
            preencherDados(aluno);
            alterar = true;
            getBtnAlterar().setEnabled(false);
            getBtnExcluir().setEnabled(false);
            getTbAluno().setEnabled(false);
        }
    }
    
    private void tbAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAlunoMouseClicked

        if(evt.getClickCount() == 2){
            if(getTbAluno().getSelectedRow() > -1)
                alterarAluno();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tbAlunoMouseClicked

    private void excluirAluno() {

        DefaultTableModel model = (DefaultTableModel) getTbAluno().getModel();
        String cpf = (String) model.getValueAt(getTbAluno().getSelectedRow(), 0);

        Aluno aluno = new Aluno();
        aluno.setCpf(cpf);
        int index = getListAlunos().indexOf(aluno);

        if (index > -1) {
            getListAlunos().remove(index);
            model.removeRow(getTbAluno().getSelectedRow());
            JOptionPane.showMessageDialog(this, "Aluno excluído com sucesso!", "Confirmação de exclusão", JOptionPane.INFORMATION_MESSAGE);
            limparDados();
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<String> cbCurso;
    private javax.swing.JComboBox<String> cbDepartamento;
    private javax.swing.JFormattedTextField ftfCpf;
    private javax.swing.JFormattedTextField ftfDataNasc;
    private javax.swing.JFormattedTextField ftfMatricula;
    private javax.swing.JLabel lCpf;
    private javax.swing.JLabel lCurso;
    private javax.swing.JLabel lDataNasc;
    private javax.swing.JLabel lEndereco;
    private javax.swing.JLabel lMatricula;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lbDepartamento;
    private javax.swing.JPanel pBotoes;
    private javax.swing.JPanel pBotoesTabela;
    private javax.swing.JPanel pInfAluno;
    private javax.swing.JPanel pInfBasicas;
    private javax.swing.JPanel pSexo;
    private javax.swing.JPanel pTabelaAluno;
    private javax.swing.JRadioButton rbFem;
    private javax.swing.JRadioButton rbMasc;
    private javax.swing.JScrollPane spTabelaAluno;
    private javax.swing.JTable tbAluno;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the bgSexo
     */
    public javax.swing.ButtonGroup getBgSexo() {
        return bgSexo;
    }

    /**
     * @param bgSexo the bgSexo to set
     */
    public void setBgSexo(javax.swing.ButtonGroup bgSexo) {
        this.bgSexo = bgSexo;
    }

    /**
     * @return the btnCancelar
     */
    public javax.swing.JButton getBtnCancelar() {
        return btnCancelar;
    }

    /**
     * @param btnCancelar the btnCancelar to set
     */
    public void setBtnCancelar(javax.swing.JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    /**
     * @return the btnOk
     */
    public javax.swing.JButton getBtnOk() {
        return btnOk;
    }

    /**
     * @param btnOk the btnOk to set
     */
    public void setBtnOk(javax.swing.JButton btnOk) {
        this.btnOk = btnOk;
    }

    /**
     * @return the cbCurso
     */
    public javax.swing.JComboBox<String> getCbCurso() {
        return cbCurso;
    }

    /**
     * @param cbCurso the cbCurso to set
     */
    public void setCbCurso(javax.swing.JComboBox<String> cbCurso) {
        this.cbCurso = cbCurso;
    }

    /**
     * @return the cbDepartamento
     */
    public javax.swing.JComboBox<String> getCbDepartamento() {
        return cbDepartamento;
    }

    /**
     * @param cbDepartamento the cbDepartamento to set
     */
    public void setCbDepartamento(javax.swing.JComboBox<String> cbDepartamento) {
        this.cbDepartamento = cbDepartamento;
    }

    /**
     * @return the ftfCpf
     */
    public javax.swing.JFormattedTextField getFtfCpf() {
        return ftfCpf;
    }

    /**
     * @param ftfCpf the ftfCpf to set
     */
    public void setFtfCpf(javax.swing.JFormattedTextField ftfCpf) {
        this.ftfCpf = ftfCpf;
    }

    /**
     * @return the ftfDataNasc
     */
    public javax.swing.JFormattedTextField getFtfDataNasc() {
        return ftfDataNasc;
    }

    /**
     * @param ftfDataNasc the ftfDataNasc to set
     */
    public void setFtfDataNasc(javax.swing.JFormattedTextField ftfDataNasc) {
        this.ftfDataNasc = ftfDataNasc;
    }

    /**
     * @return the ftfMatricula
     */
    public javax.swing.JFormattedTextField getFtfMatricula() {
        return ftfMatricula;
    }

    /**
     * @param ftfMatricula the ftfMatricula to set
     */
    public void setFtfMatricula(javax.swing.JFormattedTextField ftfMatricula) {
        this.ftfMatricula = ftfMatricula;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return getpBotoes();
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.setpBotoes(jPanel1);
    }

    /**
     * @return the lCpf
     */
    public javax.swing.JLabel getlCpf() {
        return lCpf;
    }

    /**
     * @param lCpf the lCpf to set
     */
    public void setlCpf(javax.swing.JLabel lCpf) {
        this.lCpf = lCpf;
    }

    /**
     * @return the lCurso
     */
    public javax.swing.JLabel getlCurso() {
        return lCurso;
    }

    /**
     * @param lCurso the lCurso to set
     */
    public void setlCurso(javax.swing.JLabel lCurso) {
        this.lCurso = lCurso;
    }

    /**
     * @return the lDataNasc
     */
    public javax.swing.JLabel getlDataNasc() {
        return lDataNasc;
    }

    /**
     * @param lDataNasc the lDataNasc to set
     */
    public void setlDataNasc(javax.swing.JLabel lDataNasc) {
        this.lDataNasc = lDataNasc;
    }

    /**
     * @return the lEndereco
     */
    public javax.swing.JLabel getlEndereco() {
        return lEndereco;
    }

    /**
     * @param lEndereco the lEndereco to set
     */
    public void setlEndereco(javax.swing.JLabel lEndereco) {
        this.lEndereco = lEndereco;
    }

    /**
     * @return the lMatricula
     */
    public javax.swing.JLabel getlMatricula() {
        return lMatricula;
    }

    /**
     * @param lMatricula the lMatricula to set
     */
    public void setlMatricula(javax.swing.JLabel lMatricula) {
        this.lMatricula = lMatricula;
    }

    /**
     * @return the lNome
     */
    public javax.swing.JLabel getlNome() {
        return lNome;
    }

    /**
     * @param lNome the lNome to set
     */
    public void setlNome(javax.swing.JLabel lNome) {
        this.lNome = lNome;
    }

    /**
     * @return the lbDepartamento
     */
    public javax.swing.JLabel getLbDepartamento() {
        return lbDepartamento;
    }

    /**
     * @param lbDepartamento the lbDepartamento to set
     */
    public void setLbDepartamento(javax.swing.JLabel lbDepartamento) {
        this.lbDepartamento = lbDepartamento;
    }

    /**
     * @return the pInfAluno
     */
    public javax.swing.JPanel getpInfAluno() {
        return pInfAluno;
    }

    /**
     * @param pInfAluno the pInfAluno to set
     */
    public void setpInfAluno(javax.swing.JPanel pInfAluno) {
        this.pInfAluno = pInfAluno;
    }

    /**
     * @return the pInfBasicas
     */
    public javax.swing.JPanel getpInfBasicas() {
        return pInfBasicas;
    }

    /**
     * @param pInfBasicas the pInfBasicas to set
     */
    public void setpInfBasicas(javax.swing.JPanel pInfBasicas) {
        this.pInfBasicas = pInfBasicas;
    }

    /**
     * @return the pSexo
     */
    public javax.swing.JPanel getpSexo() {
        return pSexo;
    }

    /**
     * @param pSexo the pSexo to set
     */
    public void setpSexo(javax.swing.JPanel pSexo) {
        this.pSexo = pSexo;
    }

    /**
     * @return the rbFem
     */
    public javax.swing.JRadioButton getRbFem() {
        return rbFem;
    }

    /**
     * @param rbFem the rbFem to set
     */
    public void setRbFem(javax.swing.JRadioButton rbFem) {
        this.rbFem = rbFem;
    }

    /**
     * @return the rbMasc
     */
    public javax.swing.JRadioButton getRbMasc() {
        return rbMasc;
    }

    /**
     * @param rbMasc the rbMasc to set
     */
    public void setRbMasc(javax.swing.JRadioButton rbMasc) {
        this.rbMasc = rbMasc;
    }

    /**
     * @return the tfEndereco
     */
    public javax.swing.JTextField getTfEndereco() {
        return tfEndereco;
    }

    /**
     * @param tfEndereco the tfEndereco to set
     */
    public void setTfEndereco(javax.swing.JTextField tfEndereco) {
        this.tfEndereco = tfEndereco;
    }

    /**
     * @return the tfNome
     */
    public javax.swing.JTextField getTfNome() {
        return tfNome;
    }

    /**
     * @param tfNome the tfNome to set
     */
    public void setTfNome(javax.swing.JTextField tfNome) {
        this.tfNome = tfNome;
    }

    /**
     * @return the btnAlterar
     */
    public javax.swing.JButton getBtnAlterar() {
        return btnAlterar;
    }

    /**
     * @param btnAlterar the btnAlterar to set
     */
    public void setBtnAlterar(javax.swing.JButton btnAlterar) {
        this.btnAlterar = btnAlterar;
    }

    /**
     * @return the btnExcluir
     */
    public javax.swing.JButton getBtnExcluir() {
        return btnExcluir;
    }

    /**
     * @param btnExcluir the btnExcluir to set
     */
    public void setBtnExcluir(javax.swing.JButton btnExcluir) {
        this.btnExcluir = btnExcluir;
    }

    /**
     * @return the pBotoes
     */
    public javax.swing.JPanel getpBotoes() {
        return pBotoes;
    }

    /**
     * @param pBotoes the pBotoes to set
     */
    public void setpBotoes(javax.swing.JPanel pBotoes) {
        this.pBotoes = pBotoes;
    }

    /**
     * @return the pBotoesTabela
     */
    public javax.swing.JPanel getpBotoesTabela() {
        return pBotoesTabela;
    }

    /**
     * @param pBotoesTabela the pBotoesTabela to set
     */
    public void setpBotoesTabela(javax.swing.JPanel pBotoesTabela) {
        this.pBotoesTabela = pBotoesTabela;
    }

    /**
     * @return the pTabelaAluno
     */
    public javax.swing.JPanel getpTabelaAluno() {
        return pTabelaAluno;
    }

    /**
     * @param pTabelaAluno the pTabelaAluno to set
     */
    public void setpTabelaAluno(javax.swing.JPanel pTabelaAluno) {
        this.pTabelaAluno = pTabelaAluno;
    }

    /**
     * @return the spTabelaAluno
     */
    public javax.swing.JScrollPane getSpTabelaAluno() {
        return spTabelaAluno;
    }

    /**
     * @param spTabelaAluno the spTabelaAluno to set
     */
    public void setSpTabelaAluno(javax.swing.JScrollPane spTabelaAluno) {
        this.spTabelaAluno = spTabelaAluno;
    }

    /**
     * @return the tbAluno
     */
    public javax.swing.JTable getTbAluno() {
        return tbAluno;
    }

    /**
     * @param tbAluno the tbAluno to set
     */
    public void setTbAluno(javax.swing.JTable tbAluno) {
        this.tbAluno = tbAluno;
    }
}
